spring:
  datasource:
    url: jdbc:mysql://101.132.195.170:3306/bifrost?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
